apiVersion: v2
name: azure-app-exporter
description: Exposing Prometheus Metrics for Azure Service Principals
type: application
version: 0.3.1
appVersion: "0.1.36"
keywords:
  - azure
  - prometheus
home: https://github.com/dodevops/azure-app-exporter
sources:
  - https://github.com/dodevops/azure-app-exporter
icon: https://raw.githubusercontent.com/dodevops/azure-app-exporter/main/logo.png
maintainers:
  - name: Marcel KÃ¶rtgen
    email: marcel.koertgen@gmail.com
    url: https://github.com/mkoertgen
  - name: DO! DevOps
    email: info@dodevops.io
    url: https://github.com/dodevops
